In [1]:
import pandas as pd
from numpy import array
from numpy import argmax
from keras.utils import to_categorical

Using TensorFlow backend.


In [38]:
user_features=pd.read_csv("users.csv")

In [3]:
for i in range(len(user_features["gender"])):
    if(user_features["gender"][i]=="M"):
        user_features["gender"][i]=0
    else:
        user_features["gender"][i]=1
print(user_features["gender"])

C:\Users\hp\anaconda3.0\envs\keras_env\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\hp\anaconda3.0\envs\keras_env\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


0      0
1      1
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     1
15     0
16     1
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
913    0
914    0
915    0
916    1
917    0
918    1
919    1
920    0
921    0
922    0
923    0
924    0
925    0
926    0
927    0
928    0
929    0
930    1
931    0
932    0
933    0
934    1
935    0
936    0
937    1
938    1
939    1
940    0
941    0
942    0
Name: gender, Length: 943, dtype: object


In [4]:
for i in range(len(user_features["age"])):
    if(user_features["age"][i]<=10):
        user_features["age"][i]=0
    else:
        if(user_features["age"][i]<=20):
            user_features["age"][i]=1
        else:
            if(user_features["age"][i]<=30):
                user_features["age"][i]=2
            else:
                if(user_features["age"][i]<=40):
                    user_features["age"][i]=3
                else:
                    if(user_features["age"][i]<50):
                        user_features["age"][i]=4
                    else:
                        if(user_features["age"][i]<=60):
                            user_features["age"][i]=5
                        else:
                            if(user_features["age"][i]<=70):
                                user_features["age"][i]=6
                            else:
                                if(user_features["age"][i]<=80):
                                    user_features["age"][i]=7

C:\Users\hp\anaconda3.0\envs\keras_env\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Users\hp\anaconda3.0\envs\keras_env\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\hp\anaconda3.0\envs\keras_env\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\hp\anaconda3.0\envs\keras_env\lib\site-package

In [5]:
user_features["occupation"]=user_features["occupation"].astype('category')
user_features["occupation"]=user_features["occupation"].cat.codes
user_features

user_id  age gender  occupation
0          1    3      0          13
1          2    1      1          18
2          3    2      0           3
3          4    2      0          14
4          5    1      0          18
5          6    2      0          19
6          7    5      0          19
7          8    3      0          14
8          9    2      0          14
9         10    6      0          15
10        11    1      0          18
11        12    3      0          13
12        13    1      0          18
13        14    3      0           4
14        15    1      1          18
15        16    3      0           4
16        17    5      1           0
17        18    3      0          13
18        19    3      0          14
19        20    3      0           3
20        21    4      0          13
21        22    2      0           0
22        23    2      0          14
23        24    1      0          18
24        25    4      0           5
25        26    6      0           4
26        27    4      0           0
27        28    4      0           1
28        29    3      0          14
29        30    3      0          13
..       ...  ...    ...         ...
913      914    4      0           4
914      915    2      0           1
915      916    2      0          18
916      917    3      1          20
917      918    3      0          18
918      919    3      1           3
919      920    2      1          14
920      921    3      0          14
921      922    1      0          18
922      923    2      0           3
923      924    2      0          18
924      925    2      0          18
925      926    2      0          18
926      927    4      0          13
927      928    3      0          17
928      929    3      0          17
929      930    2      0           9
930      931    3      1           0
931      932    3      0          14
932      933    3      0           1
933      934    2      0          13
934      935    2      1           0
935      936    2      0          13
936      937    3      0          13
937      938    3      1          18
938      939    3      1           3
939      940    2      1          20
940      941    4      0          13
941      942    5      0          13
942      943    5      0          14

[943 rows x 4 columns]

In [6]:
from numpy import array
from numpy import argmax
from keras.utils import to_categorical
# define example
age_encoded = user_features["age"] 
age_encoded = array(age_encoded)
# one hot encode
age_encoded = to_categorical(age_encoded)
print(age_encoded)

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  1.  0. ...,  0.  0.  0.]
 [ 0.  0.  1. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  1.  0.  0.]
 [ 0.  0.  0. ...,  1.  0.  0.]]


In [7]:
# define example
gender_encoded = user_features["gender"] 
gender_encoded = array(gender_encoded)
# one hot encode
gender_encoded = to_categorical(gender_encoded)
print(gender_encoded)

[[ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 ..., 
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]]


In [8]:
# define example
occupation_encoded = user_features["occupation"] 
occupation_encoded = array(occupation_encoded)
# one hot encode
occupation_encoded = to_categorical(occupation_encoded)
print(occupation_encoded)

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  1.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [9]:
movie_features=pd.read_csv("movies.csv")

In [10]:
movie_features=movie_features.drop(["movie_title","release_date","IMDb URL"],axis=1)

In [11]:
movie_features_2=movie_features.drop("movie_id",axis=1)

In [12]:
movie_features_2=array(movie_features_2)

In [13]:
ratings=pd.read_csv("ratings_train.csv")

In [14]:
rating_matrix = ratings.pivot(index = 'user_id', columns ='movie_id', values = 'rating').fillna(0)

In [15]:
print(movie_features_2)

[[0 0 0 ..., 0 0 0]
 [0 1 1 ..., 1 0 0]
 [0 0 0 ..., 1 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [16]:
movie_features_2

(1682, 19)

In [17]:
age_encoded.shape

(943, 8)

In [52]:
import numpy as np 
user=np.zeros((943,32))

In [53]:
user[:,0:8]=age_encoded

In [54]:
user[:,8:10]=gender_encoded

In [57]:
user[:,10:31]=occupation_encoded

In [63]:
user[:,31]=rr

In [77]:
print(user.shape)

(943, 32)


In [78]:
x=np.zeros((80000,52))

In [75]:
for i in range(80000):
    a1=ratings["user_id"][i]
    a2=ratings["movie_id"][i]
    t1=user[a1-1]
    t2=mv_2[a2-1]
    x[i,:32]=t1
    x[i,32:]=t2

ValueError: could not broadcast input array from shape (20) into shape (18)

In [26]:
print(x.shape)

(80000, 50)


In [27]:
y=ratings["rating"]

In [28]:
print(y.shape)

(80000,)


In [29]:
from sklearn.linear_model import LinearRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics

C:\Users\hp\anaconda3.0\envs\keras_env\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [30]:
linear_regression_model=LinearRegression(normalize=True)

In [31]:
tr_x,ts_x,tr_y,ts_y=train_test_split(x,y,train_size=0.7)

In [32]:
linear_regression_model.fit(tr_x,tr_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [33]:
pred=linear_regression_model.predict(ts_x)

In [34]:
acc=linear_regression_model.score(ts_x,ts_y)

In [35]:
max(pred)

4.5353507995605469

In [36]:
min(pred)

2.1983299255371094

In [62]:
rr=np.zeros((943))
n=np.zeros((943))
for j in range(80000):
    rr[ratings["user_id"]-1]+=ratings["rating"]
    n[ratings["user_id"]-1]+=1
for j in range(943):
    if n[j]!=0:
        rr[j]=float(rr[j]/n[j])

In [64]:
rr2=np.zeros((1682))
n2=np.zeros((1682))
for j in range(80000):
    rr2[ratings["movie_id"]-1]+=ratings["rating"]
    n2[ratings["movie_id"]-1]+=1
for j in range(1682):
    if n2[j]!=0:
        rr2[j]=float(rr2[j]/n2[j])

In [50]:
xx=np.zeros((80000,52))

ValueError: could not broadcast input array from shape (943,1) into shape (80000)

In [61]:
np.zeros((5))

array([ 0.,  0.,  0.,  0.,  0.])

In [67]:
mv_2=np.zeros((1682,20))

mv_2[:,:19]=movie_features_2

In [68]:
mv_2[:,:19]=movie_features_2

In [71]:
mv_2[:,19]=rr2

df

In [76]:
print(mv_2.shape)

(1682, 20)


In [79]:
for i in range(80000):
    a1=ratings["user_id"][i]
    a2=ratings["movie_id"][i]
    t1=user[a1-1]
    t2=mv_2[a2-1]
    x[i,:32]=t1
    x[i,32:]=t2

In [80]:
x.shape

(80000, 52)

In [93]:
tr_x,ts_x,tr_y,ts_y=train_test_split(x,y,train_size=0.7)
linear_regression_model.fit(tr_x,tr_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [82]:
acc=linear_regression_model.score(ts_x,ts_y)

In [83]:
print(acc)

0.0927785052985


In [246]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

model=Sequential()
model.add(Dense(60,input_dim=52,activation='relu'))

model.add(Dense(30,activation='relu'))

model.add(Dense(10,activation='relu'))
model.add(Dense(6,activation='softmax'))

In [247]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [248]:
y_hot=y

In [249]:
y_hot = array(y_hot)
# one hot encode
y_hot = to_categorical(y_hot)
print(y_hot)

[[ 0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 ..., 
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]]


In [250]:
tr_x,ts_x,tr_y,ts_y=train_test_split(x,y_hot,train_size=0.7)

In [251]:
model.fit(tr_x,tr_y,epochs=50,batch_size=500)

Epoch 1/50
56000/56000 [==============================] - 0s - loss: 0.4032 - acc: 0.8325     
Epoch 2/50
56000/56000 [==============================] - 0s - loss: 0.3832 - acc: 0.8333     
Epoch 3/50
56000/56000 [==============================] - 0s - loss: 0.3777 - acc: 0.8333     
Epoch 4/50
56000/56000 [==============================] - 0s - loss: 0.3754 - acc: 0.8334     
Epoch 5/50
56000/56000 [==============================] - 0s - loss: 0.3736 - acc: 0.8335     
Epoch 6/50
56000/56000 [==============================] - 0s - loss: 0.3726 - acc: 0.8338     
Epoch 7/50
56000/56000 [==============================] - 0s - loss: 0.3717 - acc: 0.8341     
Epoch 8/50
56000/56000 [==============================] - 0s - loss: 0.3712 - acc: 0.8342     
Epoch 9/50
56000/56000 [==============================] - 0s - loss: 0.3705 - acc: 0.8342     
Epoch 10/50
56000/56000 [==============================] - 0s - loss: 0.3699 - acc: 0.8342     
Epoch 11/50
56000/56000 [========================

In [252]:
score=model.evaluate(ts_x,ts_y)

22816/24000 [===========================>..] - ETA: 0s

In [253]:
print(score)

[0.36928295660018923, 0.83400696992874146]


In [254]:
predictions=model.predict(ts_x)

In [255]:
print(predictions)

[[  1.18322114e-05   6.03052154e-02   1.52138844e-01   4.39451516e-01
    3.00919294e-01   4.71732616e-02]
 [  2.12781215e-05   3.39867659e-02   7.99052492e-02   2.66580492e-01
    4.26638335e-01   1.92867905e-01]
 [  5.63566857e-07   1.14613533e-01   3.06795180e-01   4.15489554e-01
    1.50175378e-01   1.29257096e-02]
 ..., 
 [  1.80642819e-04   6.41064271e-02   2.43798956e-01   4.75809544e-01
    1.78282917e-01   3.78214531e-02]
 [  1.25435952e-06   2.82168370e-02   6.40869662e-02   1.84121728e-01
    4.23974872e-01   2.99598396e-01]
 [  1.85867157e-06   3.64925340e-02   5.31605594e-02   1.85984105e-01
    5.25962651e-01   1.98398277e-01]]


In [256]:
test=pd.read_csv("ratings_test.csv")

In [257]:
test

user_id  movie_id  timestamp  rating
0          752       751  888192745     NaN
1          571       230  883613337     NaN
2          616       471  891309042     NaN
3          467       250  888465973     NaN
4          129       324  883248193     NaN
5          907       474  879545415     NaN
6          110       816  885141412     NaN
7          565      1022  888528956     NaN
8          300       972  887475214     NaN
9          536       825  880133031     NaN
10          87       153  887838626     NaN
11         127       102  881695592     NaN
12         451        95  887737131     NaN
13         793        44  880951254     NaN
14         405       141  887159014     NaN
15         841        53  891354690     NaN
16         101       245  887643462     NaN
17         339       895  891296308     NaN
18         286        22  892776651     NaN
19         833       880  886920821     NaN
20         685       603  876454176     NaN
21          34       803  874791489     NaN
22         872       284  892335461     NaN
23         398       273  880915529     NaN
24         766       436  883777111     NaN
25         357       216  879867509     NaN
26         598       887  893286263     NaN
27         255       657  882403380     NaN
28         337       164  892920291     NaN
29         882       288  876298595     NaN
...        ...       ...        ...     ...
19970      560       515  889737479     NaN
19971      742       272  883512593     NaN
19972      481        29  882164645     NaN
19973      639       521  891384572     NaN
19974      550       461  888905521     NaN
19975      130         8  881975579     NaN
19976      595       687  883263008     NaN
19977       37       137  875288751     NaN
19978      692       191  881957056     NaN
19979      117       205  880356242     NaN
19980      471        14  886832374     NaN
19981      633       521  880141166     NaN
19982      366       743  877886444     NaN
19983      405       233  887160633     NaN
19984      644       274  879876736     NaN
19985      875       862  884012588     NaN
19986      633       708  881002028     NaN
19987      422       257  875320464     NaN
19988      894         7  885921598     NaN
19989      294       125  875722034     NaN
19990      574       427  879517414     NaN
19991      799       269  883504565     NaN
19992      597        13  879542690     NaN
19993      182       231  882592736     NaN
19994      805       273  874954764     NaN
19995      731       257  882621915     NaN
19996      548       135  888103673     NaN
19997      182       118  882591665     NaN
19998      251       763  881170726     NaN
19999       70       286  879434336     NaN

[20000 rows x 4 columns]

In [258]:
x3=np.zeros((20000,52))

In [259]:
for i in range(20000):
    a1=test["user_id"][i]
    a2=test["movie_id"][i]
    t1=user[a1-1]
    t2=mv_2[a2-1]
    x3[i,:32]=t1
    x3[i,32:]=t2


In [260]:
print(x3)

[[ 0.  0.  1. ...,  0.  0.  4.]
 [ 0.  0.  1. ...,  0.  0.  3.]
 [ 0.  1.  0. ...,  1.  0.  3.]
 ..., 
 [ 0.  0.  1. ...,  0.  0.  3.]
 [ 0.  0.  1. ...,  0.  0.  4.]
 [ 0.  0.  0. ...,  1.  0.  4.]]


In [261]:
pred=model.predict(x3)

In [262]:
li=[]
for i in range(20000):
    k=0
    a=0
    for j in range(6):
        if pred[i][j]>a:
            a=pred[i][j]
            k=j
    li.append(k)        

In [263]:
print(li)

[5, 4, 5, 3, 4, 5, 1, 5, 3, 4, 4, 4, 4, 3, 3, 5, 4, 4, 5, 4, 4, 5, 3, 4, 4, 4, 3, 4, 3, 3, 5, 4, 4, 4, 5, 3, 3, 1, 4, 4, 5, 5, 5, 4, 4, 4, 4, 4, 4, 3, 4, 5, 4, 5, 3, 4, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 5, 5, 5, 4, 3, 2, 4, 5, 4, 5, 4, 4, 4, 4, 3, 4, 4, 5, 4, 3, 3, 4, 4, 4, 4, 5, 4, 3, 4, 3, 3, 5, 4, 5, 4, 4, 4, 4, 3, 4, 4, 4, 4, 3, 4, 4, 5, 5, 4, 3, 3, 4, 5, 4, 5, 4, 4, 4, 4, 4, 5, 3, 4, 4, 4, 3, 3, 5, 3, 5, 5, 4, 4, 3, 5, 5, 4, 5, 5, 3, 1, 3, 1, 4, 4, 4, 4, 5, 3, 4, 5, 3, 4, 5, 5, 4, 4, 4, 4, 4, 4, 5, 4, 3, 3, 3, 4, 4, 4, 5, 3, 5, 5, 4, 4, 3, 4, 3, 4, 5, 4, 3, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 4, 5, 5, 3, 4, 2, 4, 4, 5, 4, 3, 4, 4, 4, 3, 5, 4, 4, 3, 4, 5, 4, 4, 3, 4, 3, 3, 4, 3, 5, 3, 4, 3, 4, 4, 3, 4, 4, 4, 4, 4, 5, 3, 4, 4, 3, 5, 3, 5, 5, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 3, 4, 3, 4, 4, 4, 4, 3, 4, 3, 4, 4, 4, 3, 4, 4, 4, 3, 3, 3, 4, 4, 4, 1, 5, 4, 5, 4, 4, 5, 4, 4, 4, 3, 4, 5, 1, 2, 4, 4, 4, 1, 3, 5, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 5, 4, 5, 4, 4, 4, 5, 4, 4, 5, 5, 3, 4, 

In [264]:
test

user_id  movie_id  timestamp  rating
0          752       751  888192745     NaN
1          571       230  883613337     NaN
2          616       471  891309042     NaN
3          467       250  888465973     NaN
4          129       324  883248193     NaN
5          907       474  879545415     NaN
6          110       816  885141412     NaN
7          565      1022  888528956     NaN
8          300       972  887475214     NaN
9          536       825  880133031     NaN
10          87       153  887838626     NaN
11         127       102  881695592     NaN
12         451        95  887737131     NaN
13         793        44  880951254     NaN
14         405       141  887159014     NaN
15         841        53  891354690     NaN
16         101       245  887643462     NaN
17         339       895  891296308     NaN
18         286        22  892776651     NaN
19         833       880  886920821     NaN
20         685       603  876454176     NaN
21          34       803  874791489     NaN
22         872       284  892335461     NaN
23         398       273  880915529     NaN
24         766       436  883777111     NaN
25         357       216  879867509     NaN
26         598       887  893286263     NaN
27         255       657  882403380     NaN
28         337       164  892920291     NaN
29         882       288  876298595     NaN
...        ...       ...        ...     ...
19970      560       515  889737479     NaN
19971      742       272  883512593     NaN
19972      481        29  882164645     NaN
19973      639       521  891384572     NaN
19974      550       461  888905521     NaN
19975      130         8  881975579     NaN
19976      595       687  883263008     NaN
19977       37       137  875288751     NaN
19978      692       191  881957056     NaN
19979      117       205  880356242     NaN
19980      471        14  886832374     NaN
19981      633       521  880141166     NaN
19982      366       743  877886444     NaN
19983      405       233  887160633     NaN
19984      644       274  879876736     NaN
19985      875       862  884012588     NaN
19986      633       708  881002028     NaN
19987      422       257  875320464     NaN
19988      894         7  885921598     NaN
19989      294       125  875722034     NaN
19990      574       427  879517414     NaN
19991      799       269  883504565     NaN
19992      597        13  879542690     NaN
19993      182       231  882592736     NaN
19994      805       273  874954764     NaN
19995      731       257  882621915     NaN
19996      548       135  888103673     NaN
19997      182       118  882591665     NaN
19998      251       763  881170726     NaN
19999       70       286  879434336     NaN

[20000 rows x 4 columns]

In [265]:
test_2=test.drop(["user_id","timestamp"],axis=1)

In [266]:
test_2["rating"]=li

In [267]:
test_2

movie_id  rating
0           751       5
1           230       4
2           471       5
3           250       3
4           324       4
5           474       5
6           816       1
7          1022       5
8           972       3
9           825       4
10          153       4
11          102       4
12           95       4
13           44       3
14          141       3
15           53       5
16          245       4
17          895       4
18           22       5
19          880       4
20          603       4
21          803       5
22          284       3
23          273       4
24          436       4
25          216       4
26          887       3
27          657       4
28          164       3
29          288       3
...         ...     ...
19970       515       4
19971       272       4
19972        29       3
19973       521       5
19974       461       4
19975         8       4
19976       687       3
19977       137       4
19978       191       4
19979       205       4
19980        14       4
19981       521       4
19982       743       4
19983       233       2
19984       274       4
19985       862       1
19986       708       4
19987       257       5
19988         7       4
19989       125       4
19990       427       5
19991       269       4
19992        13       5
19993       231       3
19994       273       3
19995       257       3
19996       135       4
19997       118       3
19998       763       4
19999       286       4

[20000 rows x 2 columns]

In [271]:
writer=pd.ExcelWriter('output5.xlsx',engine='xlsxwriter')

In [272]:
test_2.to_excel(writer,'Sheet1')

In [273]:
writer.save()